# Assignment: Read a File into Python

Hi there,

I hear you’re the new junior data scientist on the team. Welcome!

Our polling partners just finished collecting survey data on the happiness levels in each country. I’ve attached the file.

Can you load the data into Python and confirm the number of rows in the data and the range of the happiness scores? Then we can walk through next steps together.

Thanks!\
Anna

*Attachment: happiness_survey_data.csv*

### 1. Read in data from a csv file

In [2]:
import pandas as pd

In [3]:
pd.read_csv('happiness_survey_data.csv')

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

In [4]:
pd.read_csv('happiness_survey_data.csv', sep=',', header='infer')

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

### 2. Store data in a DataFrame

In [5]:
df = pd.read_csv('happiness_survey_data.csv')

In [6]:
df

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998
3,Afghanistan,2011,3.831719,0.521104,0.495901,51.400002
4,Afghanistan,2012,3.782938,0.520637,0.530935,51.700001
...,...,...,...,...,...,...
2084,Zimbabwe,2017,3.638300,0.754147,0.752826,52.150002
2085,Zimbabwe,2018,3.616480,0.775388,0.762675,52.625000
2086,Zimbabwe,2019,2.693523,0.759162,0.631908,53.099998
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

In [7]:
df.head(3)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Afghanistan,2008,3.723590,0.450662,0.718114,50.500000
1,Afghanistan,2009,4.401778,0.552308,0.678896,50.799999
2,Afghanistan,2010,4.758381,0.539075,0.600127,51.099998

### 3. Quickly explore the data in the DataFrame

In [8]:
df.tail(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
2087,Zimbabwe,2020,3.159802,0.717243,0.643303,53.575001
2088,Zimbabwe,2021,3.154578,0.685151,0.667636,54.049999

In [9]:
df.shape

(2089, 6)

In [10]:
df.count()

country_name                        2089
year                                2089
happiness_score                     2089
social_support                      2076
freedom_to_make_life_choices        2057
healthy_life_expectancy_at_birth    2031
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089 entries, 0 to 2088
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country_name                      2089 non-null   object
 1   year                              2089 non-null   int64
 2   happiness_score                   2089 non-null   float64
 3   social_support                    2076 non-null   float64
 4   freedom_to_make_life_choices      2057 non-null   float64
 5   healthy_life_expectancy_at_birth  2031 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 98.1+ KB

In [13]:
df.dtypes

country_name                         object
year                                  int64
happiness_score                     float64
social_support                      float64
freedom_to_make_life_choices        float64
healthy_life_expectancy_at_birth    float64
dtype: object