## Reading CSV and Excel files with Pandas

In [25]:
import os
print(os.getcwd())

c:\NLP\Python\Python Projects\NLP\maven-nlp\maven-coursework

In [26]:
import pandas as pd

In [27]:
pd.read_csv('course_offerings.csv')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [28]:
# adding more arguments -> separator ',' and header
pd.read_csv('course_offerings.csv', sep=',', header='infer')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [29]:
# reading the second tab of an excel file
pd.read_excel('Course Offerings.xlsx', sheet_name=1)

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [ ]:
# connect to SQLite database
import sqlite3
conn = sqlite3.connect('../Data/maven.db')

In [35]:
pd.read_sql('SELECT * FROM courses', conn)

   course_id                       course    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [36]:
pd.read_sql('SELECT * FROM courses WHERE course_id=101', conn)

   course_id           course    instructor
0        101  Intro to Python  Chris Bruehl

## Dataframes

In [ ]:
df = pd.read_csv('course_offerings.csv')

In [44]:
df

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [45]:
# first 2 rows
df.head(2)

   course_id      course_name    instructor
0        101  Intro to Python  Chris Bruehl
1        102     Intro to SQL   John Pauler

In [43]:
# method: see the last 2 rows
df.tail(2)

   course_id                  course_name    instructor
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [47]:
# attribute: display the number of rows and columns ** shape cannot take parenthesis ()
df.shape

(5, 3)

In [48]:
# number of values in each column
df.count()

course_id      5
course_name    5
instructor     5
dtype: int64

In [49]:
# display summary stats (mean, min, max)
df.describe()

        course_id
count    5.000000
mean   207.200000
std    107.829495
min    101.000000
25%    102.000000
50%    201.000000
75%    301.000000
max    331.000000

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   course_id    5 non-null      int64
 1   course_name  5 non-null      object
 2   instructor   5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes