In [106]:
import pandas as pd

In [107]:
# reading excel file 'Run Times.xlsx' and storing it in variable run_times
run_times = pd.read_excel('Run Times.xlsx')

In [108]:
run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [109]:
# checking data types
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                     object
dtype: object

In [110]:
run_times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      object
 4   Run Date      5 non-null      datetime64[ns]
 5   Race Date     5 non-null      datetime64[ns]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      object
dtypes: bool(1), datetime64[ns](2), float64(1), object(4)
memory usage: 417.0+ bytes

In [111]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [112]:
# convert: object to numeric value
# replace all the dollar signs with nothing in the Fee column
run_times.Fee = pd.to_numeric(run_times.Fee.str.replace('$', '')) 

# 'fee' went from object -> float, and all the '$' are gone.
# save it at a variable 'run_times.Fee' for the type to change

In [113]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [114]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [115]:
# warm up time column -> numeric
pd.to_numeric(run_times['Warm Up Time'], errors ='coerce')

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [116]:
# NaN value (3 min)
run_times['Warm Up Time'] = pd.to_numeric(run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [117]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time           float64
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [118]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3.0,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [119]:
# bool to int (0,1)
run_times.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

## Missing Data

In [120]:
df = pd.read_excel('Student Grades.xlsx')
df.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [121]:
# identify missing values (returns True if found)
df.isna()

    Student  Class   Year  Grade
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
..      ...    ...    ...    ...
81     True   True   True   True
82    False   True   True   True
83     True  False  False  False
84    False  False  False   True
85    False   True   True  False

[86 rows x 4 columns]

In [122]:
# return missing values by column
df.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [123]:
df.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
81     True
82     True
83     True
84     True
85     True
Length: 86, dtype: bool

In [124]:
# displaying rows with missing values
df[df.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

## Other way to check for missing values

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     object
 1   Class    83 non-null     object
 2   Year     80 non-null     object
 3   Grade    82 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.8+ KB

In [126]:
df.Year.value_counts(dropna=False)
# 6 missing values within the column 'Year'

Year
Freshman     35
Sophomore    24
Junior       20
NaN           6
Senior        1
Name: count, dtype: int64

## Handling Missing Data

In [127]:
df[df.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

In [128]:
df.shape

(86, 4)

In [129]:
# deleting rows that dont have a Student or Class name
df = df.dropna(subset=['Student', 'Class'])
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
77    Aaron               EDA    Junior   85.0
78  Charles               EDA    Junior   93.0
79   Connor               EDA    Junior   91.0
80    Riley               EDA    Junior   87.0
84    Gavin               EDA    Senior    NaN

[82 rows x 4 columns]

In [130]:
df.shape
# now 82 rows meaning that the removal of missing data worked

(82, 4)

In [131]:
# checking missing values
df[df.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
84    Gavin                        EDA  Senior    NaN

In [132]:
# focusing on 'Grade'
df[df.Grade.isna()]

   Student                      Class    Year  Grade
62  Landon  Exploratory Data Analysis  Junior    NaN
84   Gavin                        EDA  Senior    NaN

In [133]:
# average grade -> ~85.55
df.Grade.mean()

np.float64(85.55)

In [134]:
# adding/imputing median to missing Grade
df['Grade'].fillna(df['Grade'].mean(), inplace=True)

C:\Users\lassa\AppData\Local\Temp\ipykernel_26056\2399236169.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Grade'].fillna(df['Grade'].mean(), inplace=True)

In [135]:
df.Grade
# checking if it got updated -> yes

0     86.00
1     86.00
2     86.00
3     87.00
4     90.00
      ...
77    85.00
78    93.00
79    91.00
80    87.00
84    85.55
Name: Grade, Length: 82, dtype: float64

In [136]:
df[df.isna().any(axis=1)]
# only Year data missing

   Student             Class Year  Grade
7    Jacob  Freshman Seminar  NaN   88.0
8  William  Freshman Seminar  NaN   89.0
9    Ethan  Freshman Seminar  NaN   86.0

In [137]:
df[df.Class == 'Freshman Seminar']
# all the other students in the class 'Freshman Seminar' are Freshman

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [138]:
# adding/imputing 'Freshman' to missing Year
df.loc[7, 'Year'] = 'Freshman' #  this method is one by one

In [139]:
# imputing to all the NaN values in 'Year'
import numpy as np
df.Year = np.where(df.Year.isna(), 'Freshman', df.Year)
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

In [142]:
df[df.Class == 'Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar  Freshman   88.0
8    William  Freshman Seminar  Freshman   89.0
9      Ethan  Freshman Seminar  Freshman   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [ ]:
df[df.isna().any(axis=1)]
# no missing values

Empty DataFrame
Columns: [Student, Class, Year, Grade]
Index: []