# Exploratory Data Analysis : Coursework & Notes

## Filtering

In [20]:
import pandas as pd

In [21]:
# reading the data that was previously cleaned
groceries = pd.read_pickle('groceries_with_new_columns.pkl')
groceries.head()

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percentage Inventory,Low Inventory,Last_Updated,Last_Updated_Time,New_Shipment_Date,Shipment_Date_DOW
0,P100010,100010,Produce,Fruit,Apple,False,1.50,349,7.19,,2023-06-12 15:35:00,15:35:00,2023-06-16,Thursday
1,P100011,100011,Produce,Fruit,Banana,False,0.40,500,10.29,,2023-06-12 18:30:00,18:30:00,2023-06-16,Thursday
2,P100012,100012,Produce,Fruit,Grapes,False,4.00,200,4.12,,2023-06-12 17:22:00,17:22:00,2023-06-16,Thursday
3,P100013,100013,Produce,Fruit,Grapefruit,False,0.99,50,1.03,,2023-06-12 16:29:00,16:29:00,2023-06-16,Thursday
4,P100014,100014,Produce,Fruit,Organic Strawberries,True,3.99,148,3.05,,2023-06-12 18:10:00,18:10:00,2023-06-16,Thursday

In [22]:
# filtering through 'low inventory' section
groceries.loc[groceries['Low Inventory'] == 'Low Inventory', ['Price_Dollars', 'Inventory']]

    Price_Dollars  Inventory
15           4.49         32
17           1.50         27
20           2.99          5

In [27]:
# filtering through the 'subcategory' section
groceries[groceries.Subcategory == 'Snacks']
# output is empty because it is inputed with a space ' Fruit'

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percentage Inventory,Low Inventory,Last_Updated,Last_Updated_Time,New_Shipment_Date,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.56,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,Chips,False,2.50,365,7.51,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,Cookies (Oatmeal),False,5.39,340,7.00,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.10,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [26]:
groceries.Subcategory[0]

'Fruit'

In [ ]:
# remove the space: ' Fruit' -> 'Fruit'
groceries.Subcategory = groceries.Subcategory.str.strip()

In [28]:
# filtering with multiple conditions
mask = (groceries['Low Inventory'] == 'Low Inventory') & (groceries.Subcategory == 'Snacks')

In [ ]:
# this will show columns that both have Low Inventory and Snacks
groceries[mask]

,Product_ID,Product_ID_Num,Category,Subcategory,Item,Organic,Price_Dollars,Inventory,Percentage Inventory,Low Inventory,Last_Updated,Last_Updated_Time,New_Shipment_Date,Shipment_Date_DOW
17,P100027,100027,Pantry,Snacks,Apple Sauce - organic,True,1.50,27,0.56,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,Raisins,False,2.99,5,0.10,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday

In [30]:
# filtering w multiple conditions and columns
groceries.loc[mask, ['Subcategory', 'Item', 'Inventory']]

   Subcategory                   Item  Inventory
17      Snacks  Apple Sauce - organic         27
20      Snacks                Raisins          5

## Sorting